name = "Jinja2 (INI)"
grammar = "jinja2"
path_suffixes = ["ini.jinja", "ini.jinja2", "ini.j2", "cfg.jinja", "cfg.jinja2", "cfg.j2"]
block_comment = ["{#", "#}"]
autoclose_before = " \t\n\r;:.,=}])>"
brackets = [
  { start = "{%", end = "%}", close = true, newline = false },
  { start = "{{", end = "}}", close = true, newline = false },
  { start = "{#", end = "#}", close = true, newline = false },
  { start = "(", end = ")", close = true, newline = false },
  { start = "[", end = "]", close = true, newline = false },
]
scope_opt_in_language_servers = [
  "jinja2-lsp",
  "vscode-jinja",
]

increase_indent_pattern = "^\\s*\\{%\\s*(if|for|with|block|filter|macro|autoescape|trans|pluralize|call)\\b"
decrease_indent_pattern = "^\\s*\\{%\\s*(end(if|for|with|block|filter|macro|autoescape|trans|pluralize|call)|else|elif)\\b"
