id = "jinja2"
name = "Jinja2"
version = "0.0.1"
schema_version = 1
authors = ["Alex Oleshkevich <alex.oleshkevich@gmail.com>"]
description = "Jinja 2 extension for Zed"
repository = "https://github.com/alex-oleshkevich/zed-extension-jinja2"

[grammars.jinja2]
repository = "https://github.com/alex-oleshkevich/tree-sitter-jinja2"
rev = "master"

