name = "Jinja2 (HTML)"
grammar = "jinja2"
path_suffixes = ["html.jinja", "html.jinja2", "html.j2", "htm.j2", "htm.jinja", "htm.jinja2"]
line_comments = ["{#", "#}"]
block_comment = ["{# ", " #}"]
language_servers = ["jinja2-lsp", "..."]
brackets = [
    { start = "{", end = "}", close = true, newline = false },
    { start = "(", end = ")", close = true, newline = false },
    { start = "[", end = "]", close = true, newline = false },
    { start = "<", end = ">", close = true, newline = false },
    { start = "{{", end = "}}", close = true, newline = false, not_in = ["comment", "string"] },
    { start = "{%", end = "%}", close = true, newline = false, not_in = ["comment", "string"] },
    { start = "{#", end = "#}", close = true, newline = false, not_in = ["comment", "string"] },
    { start = "\"", end = "\"", close = true, newline = false, not_in = ["comment", "string"] },
    { start = "'", end = "'", close = true, newline = false, not_in = ["comment", "string"] },
]
