name = "Jinja2 (GraphQL)"
grammar = "jinja2"
path_suffixes = ["graphql.jinja", "graphql.jinja2", "graphql.j2", "gql.jinja", "gql.jinja2", "gql.j2"]
line_comments = ["{#", "#}"]
block_comment = ["{# ", " #}"]
brackets = [
  { start = "{%", end = "%}", close = true, newline = false },
  { start = "{{", end = "}}", close = true, newline = false },
  { start = "{#", end = "#}", close = true, newline = false },
  { start = "(", end = ")", close = true, newline = false },
  { start = "[", end = "]", close = true, newline = false },
  { start = "{", end = "}", close = true, newline = true },
]
scope_opt_in_language_servers = [
  "jinja2-lsp",
  "vscode-jinja",
]
