name = "Jinja2 (Plain Text)"
grammar = "jinja2"
path_suffixes = ["txt.jinja", "txt.jinja2", "txt.j2"]
line_comments = ["{#", "#}"]
block_comment = ["{# ", " #}"]
brackets = [
  { start = "{%", end = "%}", close = true, newline = false },
  { start = "{{", end = "}}", close = true, newline = false },
  { start = "{#", end = "#}", close = true, newline = false },
  { start = "(", end = ")", close = true, newline = false },
  { start = "[", end = "]", close = true, newline = false },
]
scope_opt_in_language_servers = [
  "jinja2-lsp",
  "vscode-jinja",
]
