name = "Jinja2 (YAML)"
grammar = "jinja2"
path_suffixes = ["yaml.jinja", "yaml.jinja2", "yaml.j2", "yml.jinja", "yml.jinja2", "yml.j2"]
line_comments = ["{#", "#}"]
block_comment = ["{# ", " #}"]
brackets = [
  { start = "{%", end = "%}", close = true, newline = false },
  { start = "{{", end = "}}", close = true, newline = false },
  { start = "{#", end = "#}", close = true, newline = false },
  { start = "(", end = ")", close = true, newline = false },
  { start = "[", end = "]", close = true, newline = false },
]
scope_opt_in_language_servers = [
  "jinja2-lsp",
  "vscode-jinja",
]
